# Generated by Django 5.2.15 on 2026-06-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_payment_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productview',
            new_name='store_produ_session_f1fef4_idx',
            old_name='store_produ_session_6e8f2a_idx',
        ),
        migrations.RenameIndex(
            model_name='productview',
            new_name='store_produ_user_id_93c5a9_idx',
            old_name='store_produ_user_id_8c4b1e_idx',
        ),
        migrations.RenameIndex(
            model_name='productview',
            new_name='store_produ_medicin_57a4cc_idx',
            old_name='store_produ_medicin_2a9f3d_idx',
        ),
    ]
