services:
  - type: web
    name: pharmos
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: gunicorn farmos.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: KAGGLE_USERNAME
        sync: false
      - key: KAGGLE_KEY
        sync: false
      - key: NEON_DB_HOST
        sync: false
      - key: NEON_DB_NAME
        sync: false
      - key: NEON_DB_USER
        sync: false
      - key: NEON_DB_PASSWORD
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
